prometheusSpec:
  ## Prometheus StorageSpec for persistent data
  ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md
  ##
  storageSpec:
    volumeClaimTemplate:
        spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 10Gi    

prometheusOperator:
  createCustomResource: false
